<a href="https://colab.research.google.com/github/2303A52012/2024-Stat-ML-Assignments/blob/main/2303A52012(Sml)Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Question 1**
1. **Read the data with pandas and find features and target variables**
2. **Normalize the data with min-max scaling**
3. **Split the data into train and test.**

## **Reading data**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
train = pd.read_csv('train.csv')

In [ ]:
train

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

## **1.features and target variables and of train**
****

### **1.a.target variable**

In [ ]:
y=train['price_range']
print(f"the target variable is {y.name} \nand the data is \n")
print(y)
print(f"the range of target variable is {y.min()} - {y.max()}")

the target variable is price_range
and the data is

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64
the range of target variable is 0 - 3

### **1.b.features**

In [ ]:
x=train.drop('price_range',axis=1)
print(f"the features are")
for i in x.columns:
  print(i , end=" , ")
print(f"\nand the data is \n")
print(x)

the features are
battery_power , blue , clock_speed , dual_sim , fc , four_g , int_memory , m_dep , mobile_wt , n_cores , pc , px_height , px_width , ram , sc_h , sc_w , talk_time , three_g , touch_screen , wifi ,
and the data is

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]

## **2.Normalize the data with min-max scaling**

In [ ]:
normilize_x=(x-x.min())/(x.max()-x.min())
normilize_x

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,0.227789,0.0,0.68,0.0,0.052632,0.0,0.080645,0.555556,0.900000,0.142857,0.10,0.010204,0.170895,0.612774,0.285714,0.388889,0.944444,0.0,0.0,1.0
1,0.347361,1.0,0.00,1.0,0.000000,1.0,0.822581,0.666667,0.466667,0.285714,0.30,0.461735,0.993324,0.634687,0.857143,0.166667,0.277778,1.0,1.0,0.0
2,0.041416,1.0,0.00,1.0,0.105263,1.0,0.629032,0.888889,0.541667,0.571429,0.30,0.644388,0.811749,0.627205,0.428571,0.111111,0.388889,1.0,1.0,0.0
3,0.076152,1.0,0.80,0.0,0.000000,0.0,0.129032,0.777778,0.425000,0.714286,0.45,0.620408,0.858478,0.671566,0.785714,0.444444,0.500000,1.0,0.0,0.0
4,0.881764,1.0,0.28,0.0,0.684211,1.0,0.677419,0.555556,0.508333,0.142857,0.70,0.616327,0.475300,0.308658,0.214286,0.111111,0.722222,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.195725,1.0,0.00,1.0,0.000000,1.0,0.000000,0.777778,0.216667,0.714286,0.70,0.623469,0.927904,0.110102,0.571429,0.222222,0.944444,1.0,1.0,0.0
1996,0.977956,1.0,0.84,1.0,0.000000,0.0,0.596774,0.111111,0.891667,0.428571,0.15,0.466837,0.977971,0.474613,0.428571,0.555556,0.777778,1.0,1.0,1.0
1997,0.941884,0.0,0.16,1.0,0.052632,1.0,0.548387,0.666667,0.233333,1.000000,0.15,0.442857,0.755674,0.748530,0.285714,0.055556,0.166667,1.0,1.0,0.0
1998,0.675351,0.0,0.16,0.0,0.210526,1.0,0.709677,0.000000,0.541667,0.571429,0.25,0.171429,0.113485,0.163816,0.928571,0.555556,0.944444,1.0,1.0,1.0
1999,0.006012,1.0,0.60,1.0,0.263158,1.0,0.693548,0.888889,0.733333,0.714286,0.80,0.246429,0.169559,0.978888,1.000000,0.222222,0.000000,1.0,1.0,1.0

## **3.test and train**

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(normilize_x,y,test_size=0.2,random_state=30)
#test_size is for taking the persentage to be taken for test(a%)(range from 0-1)
#train_size is for taking the persentage to be taken for train(100-a%)(range from 0-1)
#random_state is for shuffling the data in 30 they split for a% for test and 100-a% for train
print(f"the x_train is \n{x_train}")
print(f"the x_test is \n{x_test}")
print(f"the shape of x_train is \n{x_train.shape}")
print(f"the shape of x_test is \n{x_test.shape}")

the x_train is
      battery_power  blue  clock_speed  dual_sim        fc  four_g  \
1572       0.263193   0.0         0.00       1.0  0.315789     0.0
1442       0.315297   0.0         0.00       1.0  0.263158     0.0
1516       0.387442   1.0         0.56       1.0  0.684211     1.0
259        0.706747   1.0         0.44       1.0  0.315789     1.0
945        0.221109   0.0         0.24       0.0  0.000000     1.0
...             ...   ...          ...       ...       ...     ...
500        0.519038   1.0         0.00       1.0  0.052632     0.0
1837       0.321977   0.0         0.04       1.0  0.000000     1.0
941        0.161657   0.0         0.00       1.0  0.000000     1.0
421        0.452238   0.0         0.68       1.0  0.315789     0.0
1829       0.376754   0.0         0.48       1.0  0.210526     1.0

      int_memory     m_dep  mobile_wt   n_cores    pc  px_height  px_width  \
1572    0.225806  0.222222   0.700000  1.000000  0.70   0.064286  0.717623
1442    0.822581  0.444444   0.966667  0.571429  0.35   0.053571  0.058745
1516    0.645161  0.000000   0.175000  0.857143  0.85   0.042347  0.210948
259     0.064516  0.444444   0.683333  0.714286  0.85   0.091327  0.706943
945     0.709677  0.222222   0.108333  0.714286  0.00   0.418367  0.578104
...          ...       ...        ...       ...   ...        ...       ...
500     0.838710  0.000000   0.200000  1.000000  0.80   0.296429  0.166889
1837    0.693548  0.000000   0.416667  0.428571  0.55   0.483673  0.470628
941     0.500000  0.222222   0.125000  0.142857  0.05   0.809694  0.773698
421     0.887097  0.222222   0.033333  0.285714  0.85   0.048980  0.568758
1829    0.741935  0.222222   0.683333  0.714286  0.40   0.606122  0.966622

           ram      sc_h      sc_w  talk_time  three_g  touch_screen  wifi
1572  0.765901  0.142857  0.000000   0.111111      0.0           0.0   1.0
1442  0.428915  0.571429  0.555556   0.777778      0.0           1.0   0.0
1516  0.587921  0.142857  0.222222   0.277778      1.0           0.0   0.0
259   0.827365  0.285714  0.055556   0.055556      1.0           1.0   1.0
945   0.818012  0.214286  0.000000   0.944444      1.0           1.0   0.0
...        ...       ...       ...        ...      ...           ...   ...
500   0.240246  0.142857  0.055556   1.000000      0.0           0.0   1.0
1837  0.479957  0.000000  0.166667   0.222222      1.0           0.0   1.0
941   0.016034  1.000000  0.555556   0.111111      1.0           0.0   0.0
421   0.597541  0.785714  0.777778   0.444444      1.0           1.0   0.0
1829  0.002405  0.214286  0.000000   0.555556      1.0           0.0   0.0

[1600 rows x 20 columns]
the x_test is
      battery_power  blue  clock_speed  dual_sim        fc  four_g  \
1856       0.858383   0.0         0.84       0.0  0.315789     0.0
364        0.277221   1.0         0.84       0.0  0.000000     0.0
1948       0.164997   0.0         0.36       0.0  0.000000     0.0
1458       0.579158   0.0         0.00       0.0  0.526316     1.0
609        0.474950   0.0         0.84       0.0  0.052632     1.0
...             ...   ...          ...       ...       ...     ...
1163       0.954576   1.0         0.60       0.0  0.578947     0.0
572        0.801603   1.0         0.00       0.0  0.684211     1.0
1105       0.674015   1.0         0.80       1.0  0.578947     0.0
1903       0.574482   1.0         0.36       0.0  0.052632     0.0
481        0.798931   1.0         0.08       0.0  0.052632     1.0

      int_memory     m_dep  mobile_wt   n_cores    pc  px_height  px_width  \
1856    0.193548  1.000000   0.291667  0.428571  0.75   0.314286  0.275033
364     0.548387  0.222222   0.958333  0.428571  0.60   0.095918  0.328438
1948    0.370968  1.000000   0.250000  0.857143  0.70   0.044898  0.139519
1458    0.645161  0.111111   0.091667  0.000000  1.00   0.462755  0.283712
609     0.709677  0.222222   0.183333  0.428571  0.40   0.311735  0.811081
...          ...       ...        ...       ...   ...        ...       ...
1163    0.225806  0.777778   0.883333  1.000000  0.60   0.969898  0.947931
572     0.709677  0.888889   0.291667  0.142857  0.75   0.185714  0.218959
1105    0.725806  0.666667   0.483333  0.142857  0.65   0.060204  0.447263
1903    0.725806  1.000000   0.741667  0.571429  0.10   0.449490  0.588785
481     0.516129  0.000000   0.125000  0.000000  0.15   0.120408  0.510013

           ram      sc_h      sc_w  talk_time  three_g  touch_screen  wifi
1856  0.743453  0.928571  0.000000   0.666667      1.0           0.0   0.0
364   0.324425  0.571429  0.000000   0.666667      0.0           1.0   0.0
1948  0.459113  0.857143  0.277778   0.611111      0.0           1.0   1.0
1458  0.356494  0.500000  0.000000   0.666667      1.0           0.0   0.0
609   0.532603  0.642857  0.166667   0.111111      1.0           1.0   1.0
...        ...       ...       ...        ...      ...           ...   ...
1163  0.408071  0.857143  0.166667   0.611111      0.0           0.0   1.0
572   0.924906  0.428571  0.000000   0.444444      1.0           1.0   0.0
1105  0.168626  0.928571  0.333333   0.166667      0.0           0.0   0.0
1903  0.598343  0.214286  0.388889   0.777778      0.0           0.0   1.0
481   0.920631  0.714286  0.500000   0.333333      1.0           1.0   0.0

[400 rows x 20 columns]
the shape of x_train is
(1600, 20)
the shape of x_test is
(400, 20)

# **Question 2**

1.  **Read the data with pandas and describe the data**
2.  F**ind data type and shape of each column**
3.  **Find the target and features**
4.  **Find the null values (if yes fill the null values with ‘0’ or mean of that column)**
5.  **Normalize all the features**
6.  **Split the data into train and test.**

## **1.Read the data with pandas and describe the data**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
data = pd.read_csv('/content/sample_data/california_housing_train.csv')
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
print(data.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000

## **2.Find data type and shape of each column**

In [ ]:
for i in data.columns:
  print(f"the data type of {i} is {data[i].dtype}")
  print(f"the shape of {i} is {data[i].shape}\n")

the data type of longitude is float64
the shape of longitude is (17000,)

the data type of latitude is float64
the shape of latitude is (17000,)

the data type of housing_median_age is float64
the shape of housing_median_age is (17000,)

the data type of total_rooms is float64
the shape of total_rooms is (17000,)

the data type of total_bedrooms is float64
the shape of total_bedrooms is (17000,)

the data type of population is float64
the shape of population is (17000,)

the data type of households is float64
the shape of households is (17000,)

the data type of median_income is float64
the shape of median_income is (17000,)

the data type of median_house_value is float64
the shape of median_house_value is (17000,)

## **3. Find the target and features**

### **target variable**

In [ ]:
y=data['median_house_value']
print(f"the target variable is {y.name} \nand the data is \n")
print(y)

the target variable is median_house_value
and the data is

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

### **features**

In [ ]:
x=data.drop('median_house_value',axis=1)
print(f"the features are")
for i in x.columns:
  print(i , end=" , ")
print(f"\nand the data is \n")
print(x)

the features are
longitude , latitude , housing_median_age , total_rooms , total_bedrooms , population , households , median_income ,
and the data is

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income
0          1015.0       472.0         1.4936
1          1129.0       463.0         1.8200
2           333.0       117.0         1.6509
3           515.0       226.0         3.1917
4           624.0       262.0         1.9250
...           ...         ...            ...
16995       907.0       369.0         2.3571
16996      1194.0       465.0         2.5179
16997      1244.0       456.0         3.0313
16998      1298.0       478.0         1.9797
16999       806.0       270.0         3.0147

[17000 rows x 8 columns]

## **4.Find the null values (if yes fill the null values with ‘0’ or mean of that column)**

In [ ]:
print(f"finding the null values \n{data.isnull()}\n\n")
print(f"the null values in data for each column are \n{data.isnull().sum()}")

finding the null values
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False
1          False     False               False        False           False
2          False     False               False        False           False
3          False     False               False        False           False
4          False     False               False        False           False
...          ...       ...                 ...          ...             ...
16995      False     False               False        False           False
16996      False     False               False        False           False
16997      False     False               False        False           False
16998      False     False               False        False           False
16999      False     False               False        False           False

       population  households  median_income  median_house_value
0           False       False          False               False
1           False       False          False               False
2           False       False          False               False
3           False       False          False               False
4           False       False          False               False
...           ...         ...            ...                 ...
16995       False       False          False               False
16996       False       False          False               False
16997       False       False          False               False
16998       False       False          False               False
16999       False       False          False               False

[17000 rows x 9 columns]


the null values in data for each column are
longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

## **5. Normalize all the features**

In [ ]:
normilize_x=(x-x.min())/(x.max()-x.min())
normilize_x

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,1.000000,0.175345,0.274510,0.147885,0.198945,0.028364,0.077454,0.068530
1,0.984064,0.197662,0.352941,0.201608,0.294848,0.031559,0.075974,0.091040
2,0.975100,0.122210,0.313725,0.018927,0.026847,0.009249,0.019076,0.079378
3,0.974104,0.116897,0.254902,0.039515,0.052142,0.014350,0.037000,0.185639
4,0.974104,0.109458,0.372549,0.038276,0.050435,0.017405,0.042921,0.098281
...,...,...,...,...,...,...,...,...
16995,0.008964,0.854410,1.000000,0.058389,0.060987,0.025337,0.060516,0.128081
16996,0.007968,0.866100,0.686275,0.061869,0.081782,0.033381,0.076303,0.139170
16997,0.004980,0.988310,0.313725,0.070515,0.082247,0.034782,0.074823,0.174577
16998,0.004980,0.984060,0.352941,0.070384,0.085506,0.036296,0.078441,0.102054
16999,0.000000,0.850159,1.000000,0.047924,0.046400,0.022506,0.044236,0.173432

## **6.Split the data into train and test.**

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(normilize_x,y,test_size=0.2,random_state=50)
#test_size is for taking the persentage to be taken for test(a%)(range from 0-1)
#train_size is for taking the persentage to be taken for train(100-a%)(range from 0-1)
#random_state is for shuffling the data in 30 they split for a% for test and 100-a% for train
print(f"the x_train is \n{x_train}")
print(f"the x_test is \n{x_test}")
print(f"the shape of x_train is \n{x_train.shape}")
print(f"the shape of x_test is \n{x_test.shape}")

the x_train is
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8730    0.574701  0.171095            0.392157     0.101595        0.084730
3796    0.638446  0.146652            0.607843     0.027705        0.031968
7169    0.599602  0.176408            0.823529     0.034875        0.039261
8882    0.554781  0.160468            0.529412     0.035350        0.033209
736     0.727092  0.004251            0.411765     0.055331        0.061763
...          ...       ...                 ...          ...             ...
14565   0.218127  0.565356            0.686275     0.088493        0.076350
15649   0.197211  0.834219            0.215686     0.099670        0.108783
10123   0.451195  0.448459            0.882353     0.057783        0.087213
5600    0.614542  0.176408            0.843137     0.038777        0.038641
14000   0.230080  0.510096            0.470588     0.052511        0.044382

       population  households  median_income
8730     0.039771    0.087815       0.546179
3796     0.029009    0.036343       0.287562
7169     0.017097    0.040618       0.214287
8882     0.013565    0.032560       0.436553
736      0.043387    0.060845       0.251852
...           ...         ...            ...
14565    0.036296    0.079263       0.528179
15649    0.055130    0.104917       0.193142
10123    0.025814    0.088966       0.062268
5600     0.018638    0.039138       0.566896
14000    0.019647    0.046374       0.502062

[13600 rows x 8 columns]
the x_test is
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14339   0.224104  0.516472            0.352941     0.028549        0.044538
14017   0.230080  0.470776            0.941176     0.020825        0.020950
1265    0.718127  0.019129            0.823529     0.028233        0.053228
12412   0.276892  0.765143            0.313725     0.042626        0.045158
4434    0.629482  0.146652            0.568627     0.037222        0.051366
...          ...       ...                 ...          ...             ...
12863   0.251992  0.506908            0.411765     0.053829        0.062228
1624    0.709163  0.049947            0.333333     0.104363        0.079143
6512    0.605578  0.149841            0.549020     0.041571        0.054314
8252    0.588645  0.132837            0.509804     0.056386        0.040192
1377    0.715139  0.022317            0.529412     0.039858        0.059435

       population  households  median_income
14339    0.028196    0.049992       0.235114
14017    0.009193    0.022365       0.325023
1265     0.018414    0.045716       0.107102
12412    0.019675    0.046703       0.135336
4434     0.036548    0.051636       0.172418
...           ...         ...            ...
12863    0.053869    0.070383       0.221397
1624     0.043107    0.077125       0.731845
6512     0.029513    0.052787       0.124529
8252     0.017714    0.039303       0.769982
1377     0.015051    0.057721       0.114019

[3400 rows x 8 columns]
the shape of x_train is
(13600, 8)
the shape of x_test is
(3400, 8)